nelmio_api_doc:
    documentation:
        info:
            title: Hesabix API document
            description: Hesabix is first open source cloud base accounting platform
            version: 0.43.2.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
