twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [
        'bootstrap_5_layout.html.twig',
        'form/captcha.html.twig'
    ]
    globals:
        Jdate: "@Jdate"
        twigFunctions: "@twigFunctions"
when@test:
    twig:
        strict_variables: true
